language: python

python:
  - '3.7'

install:
  - pip3 install -r requirements.txt

script:
  - python -m unittest discover
  - coverage erase
  - coverage run test_app.py && coverage html
after_succes:
  - codecov
deploy:
  - provider: heroku
    api_key:
      secure: LbrHd3c0EwmxzV8xVEEVpvdrW2I5+Ry4KZHreESuSp5Akd4w/mTm80WcQ7E1uuV7X8h2Wu1S7eo5OPBFk2dUFF2rpKCvlcjEILUeA1AoxDvqKGGfI4ugYRXsQ6OkWGXdd/kNGeznaRpFbnQ+1R84UrDi6hNsyhhntcp5hqq35tVhxq0WEd9GyB0PW/C1deizW+84/Q4ZFemFmKsQEs90CMW5dE5WduJbl5gek+M5WFAOHH5djM+3yKeK4ehfCtrWup5285rvldK6dAvlBxi2+AUEZ99RzXjpXWR+HNccs4KvEl57yJv8cWYBPZc72tMSm0aRQGmN+HfyfdMdSODrv6inah5+xf4bviN3M8ry/zSZlsF0s4fpcgSwz/hs5wNA1ZC2pNzv++ri7wmlaXneR2WGvVgkb1aHkqK1OJtQK6oslxgIC+WzNdgNBDt9Q1m6bAY2PEYoo9o2DFle3SOUOjw31kLaCVO63cp7XjouDmWZH3ML6IsnNDvovUukJZHAng9Yp0feVEd2zE3HPY0bAkmIpYZao6mXWvlUSrVPVd7552Y9rF6uxQ9IH8m4dpCXZbF4HAYeUZfJfYSOo13TBcMj9xGN5Oo94I99W1CnhkPcjxB/+LPRbnAaTCarGf2TgOoE0IH+tvmCHnL6ngX3661V1KWYRPRar95WRg6eOds=
    app: cisc3140-assignment-1